name: reqship.api

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, edited]
    branches: ["main", "dev"]

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build api Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
